[[constraint]]
  name = "github.com/nenadstojanovikj/rd"
  version = "0.0.7"

[[constraint]]
  name = "github.com/nenadstojanovikj/showrss-go"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "2.0.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true
