[[constraint]]
  name = "github.com/nenadstojanovikj/rd"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

#[[constraint]]
#  name = "github.com/nenadstojanovikj/showrss-go"
#  version = "0.0.1"

#[[constraint]]
#  name = "github.com/cavaliercoder/grab"
#  version = "2.0.0"

[prune]
  go-tests = true
  unused-packages = true
