[[constraint]]
  name = "github.com/nenadstojanovikj/rd"
  branch = "master"

[[constraint]]
  name = "github.com/nenadstojanovikj/trakt"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "2.0.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.10.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/qopher/go-torrentapi"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/anacrolix/torrent"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
